### ISSUE TITLE
New Policy with Frozen CLIP encoder

### ISSUE THREAD

**Issue by AnandSingh-0619** [AnandSingh-0619/home-robot#14]
[Policy Code](https://github.com/AnandSingh-0619/home-robot/blob/1461bcd5f4f46d64c703938272413cd4cd00d88c/projects/habitat_uncertainty/models/PreTrainVEPointNavResNetPolicy.py#L297C1-L364C1)

[Config file](https://github.com/AnandSingh-0619/home-robot/blob/anand_dev_heatmap_yolo/projects/habitat_uncertainty/config/rl_skill.yaml)

Here is the policy with only Pretrained CLIP visual encoder taking input only RGB and Depth image. The output from the visual encoder is tensor of size [4*2048]

**Comment by yusufali98** [comment]
What was the issue here ?

**Comment by AnandSingh-0619** [comment]
I was using only CLIP encoder for training and the success rate was very poor(<1%) even after 120M steps of training.
RGB input alone could not navigate the agent in the home-robot env.
