### ISSUE TITLE
New Fusion policy for encoders

### ISSUE THREAD

**Issue by AnandSingh-0619** [AnandSingh-0619/home-robot#15]
[Policy](https://github.com/AnandSingh-0619/home-robot/blob/anand_dev_heatmap_yolo/projects/habitat_uncertainty/models/NewPointNavResNetPolicy.py)

[Config file](https://github.com/AnandSingh-0619/home-robot/blob/anand_dev_heatmap_yolo/projects/habitat_uncertainty/config/rl_skill.yaml)

Here is the policy and config file i am using to train the policy but there is no trianing success. Can you please sanity check these?

**Comment by yusufali98** [comment]
I think these policies worked right ? And the issue here was just not training for enough number of steps ?
Can you please close this with a quick confirmation ?

**Comment by AnandSingh-0619** [comment]
Yes, the policy trained well after enough training steps.
