### ISSUE TITLE
Config File

### ISSUE THREAD

**Issue by AnandSingh-0619** [AnandSingh-0619/home-robot#4]
[Config File](https://github.com/AnandSingh-0619/home-robot/blob/anand_dev/projects/habitat_uncertainity/config/yolo_rl_skill.yaml) used for running the experiment for Gaze skill

**Comment by yusufali98** [comment]
I am guessing this is for the YOLO-RealWorld experiment ?
Can you also attach the tensorboard file + screenshots for the performance statistics ?

**Comment by yusufali98** [comment]
And also please do the same for your experiment with the original ovmm code

**Comment by AnandSingh-0619** [comment]
![image](https://github.com/AnandSingh-0619/home-robot/assets/69452312/3baa43d7-4d94-4882-a130-848429324269)
Yes this config file is for YOLO experiment

**Comment by yusufali98** [comment]
I think this issue is basically stale right now as the experiments you were running are still not on 4 GPUs and havent been run for atleast 1-2 million steps as discussed ?
If yes, you can close this issue fornow
