### ISSUE TITLE
MobileSAM batched Inference

### ISSUE THREAD

**Issue by AnandSingh-0619** [AnandSingh-0619/home-robot#5]
I am using the following links as reference
1. [Ultralytics](https://docs.ultralytics.com/models/mobile-sam/#point-prompt)
2. [Grounding SAM](https://github.com/facebookresearch/home-robot/blob/main/src/home_robot/home_robot/perception/detection/grounded_sam/grounded_sam_perception.py#L178C1-L195C38)

**Comment by yusufali98** [comment]
I think you should get deeper into the actual codebase and look at the library functions which perform the inference through the networks. Just looking at the API / example for loop code will not help much

So look through groundingDINO and ultralytics libraries and locate the exact functions which perform the inference. Then we can discuss why we can/cant send in batched bbox inputs as prompts

**Comment by AnandSingh-0619** [comment]
Not using MobileSAM hence closing this issue.

**Comment by AnandSingh-0619** [comment]
Not using MobileSAM hence closing this issue.
