### ISSUE TITLE
EOFError

### ISSUE THREAD

**Issue by AnandSingh-0619** [AnandSingh-0619/home-robot#9]
I can across this issue and unable to debug this. Can you take a look at the log file.
I have also restructured the code isolating important changes to the policy code.
https://github.com/AnandSingh-0619/home-robot/blob/fc254528c474c2f48be3a2dfbb825fb71d141057/projects/habitat_uncertainty/models/GazePointNavResNetPolicy.py#L1C1-L1060C54

[home_robo-ver-914044.log](https://github.com/user-attachments/files/15523210/home_robo-ver-914044.log)

**Comment by yusufali98** [comment]
Please run the code with `export HABITAT_ENV_DEBUG=1` to run in multi-threaded mode to better understand the error message. Repost the error log after running in multi-threaded mode.

**Comment by AnandSingh-0619** [comment]
[yolo_sam_fullres_50v2-ver-918666.log](https://github.com/user-attachments/files/15794636/yolo_sam_fullres_50v2-ver-918666.log)
Ran the code with `export HABITAT_ENV_DEBUG=1` but again code exited without any error message

**Comment by yusufali98** [comment]
Based on the log you just posted, it seems like you cancelled the slurm job so can you confirm ?
Also can you provide details of the exact experiment config + code branch that you are using for running these experiments ?

**Comment by yusufali98** [comment]
Also, can you please add some specific details of what you have been trying to debug this issue ?

**Comment by AnandSingh-0619** [comment]
Branch: [Anand_dev_YOLO_SAM](https://github.com/AnandSingh-0619/home-robot/tree/anand_dev_heatmap_yolo)
Config file: [YOLOSAM_gaze_rl_skill](https://github.com/AnandSingh-0619/home-robot/blob/anand_dev_heatmap_yolo/projects/habitat_uncertainty/config/YOLOSAM_gaze_rl_skill.yaml)
Policy: [YoloSAMPointNavResNetPolicy](https://github.com/AnandSingh-0619/home-robot/blob/anand_dev_heatmap_yolo/projects/habitat_uncertainty/models/YOLOSAMPointNavResNetPolicy.py)

I did not cancel any SLURM jobs. I just got this in the slurm_logs. 
Trying to catch the exception that might be leading to this EOFError

**Comment by yusufali98** [comment]
The [original log](https://github.com/user-attachments/files/15523210/home_robo-ver-914044.log) you posted also has this traceback:
```
Traceback (most recent call last):
  File "/srv/kira-lab/share4/asingh3064/miniforge3/envs/home-robot/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/srv/kira-lab/share4/asingh3064/miniforge3/envs/home-robot/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/nethome/asingh3064/flash/home-robot/projects/habitat_uncertainty/run.py", line 151, in <module>
    main()
  File "/nethome/asingh3064/flash/home-robot/projects/habitat_uncertainty/run.py", line 107, in main
    execute_exp(config, "train")
  File "/coc/pskynet4/asingh3064/home-robot/src/third_party/habitat-lab/habitat-baselines/habitat_baselines/run.py", line 60, in execute_exp
    trainer.train()
  File "/srv/kira-lab/share4/asingh3064/miniforge3/envs/home-robot/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/coc/pskynet4/asingh3064/home-robot/src/third_party/habitat-lab/habitat-baselines/habitat_baselines/rl/ppo/ppo_trainer.py", line 749, in train
    self.should_end_early(step + 1)
  File "/coc/pskynet4/asingh3064/home-robot/src/third_party/habitat-lab/habitat-baselines/habitat_baselines/rl/ppo/ppo_trainer.py", line 651, in should_end_early
    ) and int(self.num_rollouts_done_store.get("num_done")) >= (
RuntimeError: Socket Timeout
```

Have you investigated this ?

**Comment by AnandSingh-0619** [comment]
`def should_end_early(self, rollout_step) -> bool:`

` # This is where the preemption of workers happens.  If a detects it will be a straggler, it preempts itself!`
        
 Might be some exception in one of the workers which ended up as socket timeout

**Comment by yusufali98** [comment]
Okay got it
I remember earlier you were printing the total number of agent parameters + trainable + non-trainable parameters. But I cant see that in logs anymore so can you point me to that ?
If you have removed all that, then you need to add it back and make sure the those numbers make sense
This also applies to the [other issue](https://github.com/AnandSingh-0619/home-robot/issues/10)

**Comment by yusufali98** [comment]
Did you find a solution to this ?

**Comment by AnandSingh-0619** [comment]
This error is not very common. Maybe multi GPU task issue. Generally solved by re running the task.
